name: Test Summarize Tool

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test-summarize:
    runs-on: ubuntu-latest

    steps:
      # Step 1
      - name: Checkout summarize repository
        uses: actions/checkout@v4

      # Step 2
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'

      # Step 3
      - name: Build summarize
        run: go build -o summarize .

      # Step 4
      - name: Clone figtree repository
        run: git clone https://github.com/andreimerlescu/figtree.git

      # Test 1
      # Step 5
      - name: Run summarize on figtree (basic usage)
        run: |
          cd figtree
          ../summarize
          ls -lh summaries/

      # Step 6
      - name: Find summary file (basic usage)
        id: find-summary-basic
        run: |
          cd figtree
          SUMMARY_FILE=$(ls summaries/summary.*.md | head -n 1)
          echo "summary_file=$SUMMARY_FILE" >> $GITHUB_OUTPUT
          echo "Found summary file: $SUMMARY_FILE"

      # Step 7
      - name: Verify summary file size (basic usage)
        run: |
          SUMMARY_FILE="${{ steps.find-summary-basic.outputs.summary_file }}"
          FILE_SIZE=$(stat -c %s "$SUMMARY_FILE") # Linux
          echo "Summary file size: $FILE_SIZE bytes"
          if [ "$FILE_SIZE" -lt 1024 ]; then
            echo "Error: Summary file is less than 1KB ($FILE_SIZE bytes)"
            exit 1
          fi
          echo "Summary file size is $FILE_SIZE bytes, which is greater than 1KB"

      # Step 8
      - name: Select a random Go file (basic usage)
        id: select-file-basic
        run: |
          cd figtree
          RANDOM_FILE=$(find . -type f -name "*.go" | shuf -n 1)
          echo "random_file=$RANDOM_FILE" >> $GITHUB_OUTPUT
          echo "Selected random file: $RANDOM_FILE"

      # Step 9
      - name: Verify summary contains random file's source code (basic usage)
        run: |
          SUMMARY_FILE="${{ steps.find-summary-basic.outputs.summary_file }}"
          RANDOM_FILE="${{ steps.select-file-basic.outputs.random_file }}"
          echo "Checking if $SUMMARY_FILE contains the source code of $RANDOM_FILE"

          # Extract the section for the random file from the summary
          SECTION_START=$(grep -n "^## $RANDOM_FILE$" "$SUMMARY_FILE" | cut -d: -f1)
          if [ -z "$SECTION_START" ]; then
            echo "Error: Could not find section for $RANDOM_FILE in $SUMMARY_FILE"
            exit 1
          fi

          # Extract the code block (between ```go and ```)
          CODE_START=$((SECTION_START + 2)) # Skip the ## line and the blank line
          CODE_END=$(tail -n +$CODE_START "$SUMMARY_FILE" | grep -n "^\`\`\`$" | head -n 1 | cut -d: -f1)
          if [ -z "$CODE_END" ]; then
            echo "Error: Could not find code block end for $RANDOM_FILE in $SUMMARY_FILE"
            exit 1
          fi
          CODE_LINES=$(($CODE_END - 1))
          tail -n +$CODE_START "$SUMMARY_FILE" | head -n $CODE_LINES > extracted_code.txt

          # Read the original file content
          cat "$RANDOM_FILE" > original_code.txt

          # Compare the extracted code with the original file
          diff -wB extracted_code.txt original_code.txt > diff_output.txt
          if [ $? -ne 0 ]; then
            echo "Error: The source code in the summary does not match the original file"
            cat diff_output.txt
            exit 1
          fi
          echo "Success: The source code of $RANDOM_FILE in $SUMMARY_FILE matches the original file"

      # Test 2
      # Step 10
      - name: Create summarize config file
        run: |
          mkdir -p config
          cat <<EOF > config/summarize.config.yaml
          {"i": "go,sh,ts", "d": "$(pwd)/figtree", "o": "$(pwd)/figtree/config-summaries"}
          EOF
          cat config/summarize.config.yaml

      # Step 11
      - name: Run summarize with config file
        env:
          SUMMARIZE_CONFIG_FILE: ${{ github.workspace }}/config/summarize.config.yaml
        run: |
          cd figtree
          ../summarize
          ls -lh config-summaries/

      # Step 12
      - name: Find summary file (config usage)
        id: find-summary-config
        run: |
          cd figtree
          SUMMARY_FILE=$(ls config-summaries/summary.*.md | head -n 1)
          echo "summary_file=$SUMMARY_FILE" >> $GITHUB_OUTPUT
          echo "Found summary file: $SUMMARY_FILE"

      # Step 13
      - name: Verify summary file size (config usage)
        run: |
          SUMMARY_FILE="${{ steps.find-summary-config.outputs.summary_file }}"
          FILE_SIZE=$(stat -c %s "$SUMMARY_FILE")
          echo "Summary file size: $FILE_SIZE bytes"
          if [ "$FILE_SIZE" -lt 1024 ]; then
            echo "Error: Summary file is less than 1KB ($FILE_SIZE bytes)"
            exit 1
          fi
          echo "Summary file size is $FILE_SIZE bytes, which is greater than 1KB"

      # Test 3
      # Step 14
      - name: Create another project directory
        run: |
          mkdir -p anotherProject
          echo -e "package main\n\nfunc main() {\n    println(\"Hello, World!\")\n}" > anotherProject/hello.go
          mkdir -p custom-summaries

      # Step 15
      - name: Run summarize with command-line arguments
        run: |
          cd anotherProject
          ../summarize -d . -o ${{ github.workspace }}/custom-summaries
          ls -lh ${{ github.workspace }}/custom-summaries/

      # Step 16
      - name: Find summary file (command-line usage)
        id: find-summary-cli
        run: |
          SUMMARY_FILE=$(ls ${{ github.workspace }}/custom-summaries/summary.*.md | head -n 1)
          echo "summary_file=$SUMMARY_FILE" >> $GITHUB_OUTPUT
          echo "Found summary file: $SUMMARY_FILE"

      # Step 17
      - name: Verify summary file size (command-line usage)
        run: |
          SUMMARY_FILE="${{ steps.find-summary-cli.outputs.summary_file }}"
          FILE_SIZE=$(stat -c %s "$SUMMARY_FILE")
          echo "Summary file size: $FILE_SIZE bytes"
          if [ "$FILE_SIZE" -lt 1024 ]; then
            echo "Error: Summary file is less than 1KB ($FILE_SIZE bytes)"
            exit 1
          fi
          echo "Summary file size is $FILE_SIZE bytes, which is greater than 1KB"

      # Step 18
      - name: Verify summary contains hello.go source code (command-line usage)
        run: |
          SUMMARY_FILE="${{ steps.find-summary-cli.outputs.summary_file }}"
          RANDOM_FILE="hello.go"
          echo "Checking if $SUMMARY_FILE contains the source code of $RANDOM_FILE"

          # Extract the section for hello.go
          SECTION_START=$(grep -n "^## $RANDOM_FILE$" "$SUMMARY_FILE" | cut -d: -f1)
          if [ -z "$SECTION_START" ]; then
            echo "Error: Could not find section for $RANDOM_FILE in $SUMMARY_FILE"
            exit 1
          fi

          # Extract the code block
          CODE_START=$((SECTION_START + 2))
          CODE_END=$(tail -n +$CODE_START "$SUMMARY_FILE" | grep -n "^\`\`\`$" | head -n 1 | cut -d: -f1)
          if [ -z "$CODE_END" ]; then
            echo "Error: Could not find code block end for $RANDOM_FILE in $SUMMARY_FILE"
            exit 1
          fi
          CODE_LINES=$(($CODE_END - 1))
          tail -n +$CODE_START "$SUMMARY_FILE" | head -n $CODE_LINES > extracted_code.txt

          # Read the original file content
          cat "anotherProject/$RANDOM_FILE" > original_code.txt

          # Compare
          diff -wB extracted_code.txt original_code.txt > diff_output.txt
          if [ $? -ne 0 ]; then
            echo "Error: The source code in the summary does not match the original file"
            cat diff_output.txt
            exit 1
          fi
          echo "Success: The source code of $RANDOM_FILE in $SUMMARY_FILE matches the original file"

      # Test 4
      # Step 19
      - name: Verify summary file structure (basic usage)
        run: |
          SUMMARY_FILE="${{ steps.find-summary-basic.outputs.summary_file }}"
          # Check for the header
          grep -q "^# Project Summary" "$SUMMARY_FILE"
          if [ $? -ne 0 ]; then
            echo "Error: Summary file does not contain the expected header '# Project Summary'"
            exit 1
          fi

          # Check for at least one section with the format ## filename.ext
          grep -q "^## .*\.\(go\|ts\|tf\|sh\|py\|js\)$" "$SUMMARY_FILE"
          if [ $? -ne 0 ]; then
            echo "Error: Summary file does not contain any sections with the format '## filename.ext'"
            exit 1
          fi

          # Check for code block markers
          grep -q "```\(go\|ts\|tf\|sh\|py\|js\)" "$SUMMARY_FILE"
          if [ $? -ne 0 ]; then
            echo "Error: Summary file does not contain any code blocks with the expected language markers"
            exit 1
          fi
          echo "Success: Summary file structure is correct"